config/routes.rb
Rails.application.routes.draw do
  root 'home#top'
  get "/login", to: 'users#login_form'
  post "/login", to: "users#login"
  post "/logout", to: "users#logout"
  get "/search", to: "posts#search"
  get "/myrooms/:id", to: "users#myrooms"
  resources :users
  resources :posts do
    resources :reservations, only: [:new, :create]
  end
  resources :reservations, only: [:index,:show, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  #user・reservationモデルとの関連付け
  belongs_to :user
  has_many :resevation
  has_one_attached :image

  #各へのvalidation
  validates :room_name, presence: true
  validates :room_PR, presence: true
  validates :room_price, presence: true
  validates :room_address, presence: true

  def Post.search_area(search_area)
    Post.where(['room_address LIKE ?', "%#{search_area}%"])
  end

  def Post.search_keyword(search_keyword)
    Post.where(['room_name LIKE ? OR room_PR LIKE ? OR room_address LIKE ?',
                "%#{search_keyword}%", "%#{search_keyword}%", "%#{search_keyword}%"])
  end

end

app/models/resevation.rb
class Resevation < ApplicationRecord
#user・postモデルとの関連付け
  belongs_to :user
  belongs_to :post

#各カラムへのvalidation
validates :start_date, presence: true
validates :end_date, presence: true
validates :num_people, presence: true
end


def post
  Post.find(self.post_id)
end

app/models/user.rb
class User < ApplicationRecord
  #user・reservationモデルとの関連づけ
  has_many :posts, dependent: :destroy
  has_many :resevations, dependent: :destroy

  #各カラムへのvalidation
  validates :name, presence: true, length: {maximum: 30}
  validates :email, presence: true, length: {maximum: 255},
            uniqueness: true
            # format: { with: /\A[a-zA-Z]+\z/}
  has_secure_password
  validates :password, presence: true, length: {minimum: 8}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_current_user

  def set_current_user
    if session[:user_id]
      @current_user = User.find(session[:user_id])
    end
  end

  def authenticate_user
    unless @current_user
      flash[:danger] = "ログインしてください"
      redirect_to login_path
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user

  def new
    @post = Post.new
  end
  
  def show
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(post_params)
    @post.image.attach(params[:post][:image])
    if @post.save
      flash[:success] = "ルームを登録しました"
      redirect_to post_path(@post)
    else
      render "new"
    end
  end

  def search
    @posts = Post.search_area(params[:search_area])
    @posts = Post.search_keyword(params[:search_keyword])
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private
    def post_params
      params.require(:post).permit(:room_name, :room_PR, :room_price, :room_address, :image).merge(user_id: @current_user.id)
    end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def new
    @reservation = Resevation.new
  end

  def show
    @reservation = Resevation.find(params[:id])
    @post = @reservation.post
  end

  def create
    @reservation = Resevation.new(reservation_params)
    if @reservation.save
      redirect_to reservation_path(@reservation.id)
      flash[:success] = "予約が完了しました"
    end
  end

  def index
    @reservations = Resevation.all
  end

  def edit
  end

  def update
  end

  private
  def reservation_params
    params.permit(:start_date, :end_date, :num_people, :post_id).merge(user_id: @current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user, only: [:edit, :update, :show]

  def new
    @user = User.new
  end
 
  def myrooms
    @user = User.find(params[:id])
    @posts = @user.posts
  end

  def create
    @user = User.new(user_params)
    @user.image_name = "default_icon.jpg"
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "ユーザー登録が完了しました"
      redirect_to user_path(@user)
    else
      render "new"
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "登録情報を更新しました"
      redirect_to user_path(@user)
    else
      render "edit"
    end
  end

  def login_form
  end

  def login
    @user = User.find_by(email: params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_path
      flash[:success] = "ログインしました"
    else
      @error_message = "メールアドレスまたはパスワードが間違っています"
      render "login_form"
    end
  end

  def logout
    session[:user_id] = nil
    flash[:success] = "ログアウトしました"
    redirect_to login_path
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confrimation, :image_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/top.html.erb
<div class = top-wrapper>
  <div class = main-search>
    <h2>Potepan Shareでまだ体験したことのない旅をしよう</h2>
    <div class = "search-field">
      <p>エリア</p>
      <%= form_with( url: search_path, class: 'search_form', method: :get, local:true) do |f| %>
        <%= f.text_field :search_area, class: 'field',value: params[:search], placeholder: "東京", class: "main-input"%>
        <%= f.submit '探す', class: "main-btn" %>
      <% end %>
    </div>
  </div>
</div>
<div class = area-index-wrapper>
  <h2>おすすめのエリア</h2>
  <div class = areas>
    <div class = area>
      <div class = area-image>
        <img src="https://presite-potepancamp-rails-02.herokuapp.com/assets/img_tokyo.jpg" alt="tokyo">
        <p><%= link_to "東京", "/search?search=東京&commit=探す" %></p>
      </div>
    </div>
    <div class = area>
      <div class = area-image>
        <img src="https://presite-potepancamp-rails-02.herokuapp.com/assets/img_osaka.jpg" alt="osaka">
        <p><%= link_to "大阪", "/search?search=大阪&commit=探す" %></p>
      </div>
    </div>
    <div class = area>
      <div class = area-image>
        <img src="https://presite-potepancamp-rails-02.herokuapp.com/assets/img_kyoto.jpg" alt="kyoto">
        <p><%= link_to "京都", "/search?search=京都&commit=探す" %></p>
      </div>
    </div>
    <div class = area>
      <div class = area-image>
        <img src="https://presite-potepancamp-rails-02.herokuapp.com/assets/img_sapporo.jpg" alt="sapporo">
        <p><%= link_to "札幌", "/search?search=札幌&commit=探す" %></p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PoteShare</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
        <div class = "header-left">
        <%= link_to image_tag("https://presite-potepancamp-rails-02.herokuapp.com/assets/logo.png"), root_path%>
        </div>
        <div class = "header-left">
          <%= form_with( url: search_path, class: 'search_form_topleft', method: :get, local:true) do |f| %>
            <%= f.text_field :search_area, class: 'field',value: params[:search], placeholder: "エリア", class: "topleft-input"%>
            <%= f.submit '探す'%>
          <% end %>
        </div>
        <div class = "header-left">
          <%= form_with( url: search_path, class: 'search_form_topleft', method: :get, local:true) do |f| %>
            <%= f.text_field :search_keyword, class: 'field',value: params[:search], placeholder: "キーワード", class: "topleft-input"%>
            <%= f.submit '検索'%>
          <% end %>
        </div>
      </div>
      <div class = header-right>
        <% if @current_user%>
          <%= link_to @current_user.name, user_path(@current_user) %>
          <%= link_to "ルームを登録する", new_post_path %>
          <%= link_to "登録済みルーム", "/myrooms/#{@current_user.id}" %>
          <%= link_to "予約済みルーム", reservations_path %>
          <%= link_to "ログアウト", logout_path, method: :post %>
        <% else %>
          <%= link_to "ログイン", login_path %>
          <%= link_to "登録する", new_user_path %>
        <% end %>
      </div>
    </header>
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    <div class = "container">
      <%= yield %>
    </div>
    <footer>
      <p>© 2020 POTEPAN.INC.</p>
    </footer>
  </body>
</html>

app/views/posts/new.html.erb
<div class = room_form>
  <h2>基本情報</h2>
  <h3>ルーム情報登録</h3>
  <%= form_with model: @post, local: true do |f| %>
    <% if @post.errors.any? %>
      <ul>
        <% @post.errors.full_messages. each do |msg| %>
        <li><%= msg %></li>
      </ul>
        <% end %>
    <% end %>
    <table>
      <tr>
          <th><%= f.label :room_name ,"ルーム名" %></th>
          <td><%= f.text_field :room_name %></td>
      </tr>
      <tr>
          <th><%= f.label :room_PR ,"ルーム紹介" %></th>
          <td><%= f.text_field :room_PR %></td>
      </tr>
      <tr>
          <th><%= f.label :room_price ,"料金" %></th>
          <td><%= f.text_area :room_price %></td>
      </tr>
      <tr>
          <th><%= f.label :room_address ,"住所" %></th>
          <td><%= f.text_area :room_address %></td>
      </tr>
    </table>
    <div>
      <ul>
        <li><%= f.submit "登録"%></li>
      </ul>
    </div>
    <span class = "image">
      <%= f.file_field :image %>
    </span>
  <% end %>
</div>

app/views/posts/search.html.erb
<div class = account&profile>
  <h2>検索結果：〇〇件</h2>
    <table>
    <% @posts. each do |post| %>
      <tr>
        <th>ルームイメージ</th>
        <td><%= image_tag post.image if post.image.attached? %></td>
      </tr>
      <tr>
        <th>ルーム名</th>
        <td><%= post.room_name %></td>
      </tr>
      <tr>
        <th>エリア</th>
        <td><%= post.room_address %></td>
      </tr>
      <tr>
        <th>料金</th>
        <td><%= post.room_price %></td>
      </tr>
      <tr>
        <td><%= link_to "詳細を見る", post_path(post.id) %></td>
      </tr>
    <% end %>
    </table>
    <div>

app/views/posts/show.html.erb
<table>
	<tr>
		<th>ルームイメージ</th>
		<td><%= image_tag @post.image if @post.image.attached? %></td>
	</tr>
	<tr>
		<th>ルーム名</th>
		<td><%=@post.room_name %></td>
	</tr>
	<tr>
		<th>紹介文</th>
		<td><%=@post.room_PR %></td>
	</tr>
	<tr>
		<th>値段</th>
		<td><%=@post.room_price %> / 日</td>
	</tr>
	<tr>
		<th>住所</th>
		<td><%=@post.room_address %></td>
	</tr>
	<tr><th></th>
		<td>
			<button class = "reserve-btn">
				<%= link_to "予約する", new_post_reservation_path(@post) %>
			</button>
		</td>
	</tr>
</table>

app/views/reservations/edit.html.erb
<h1>Reservations#edit</h1>
<p>Find me in app/views/reservations/edit.html.erb</p>

app/views/reservations/index.html.erb
<div class = reservations_index>
  <h2>予約済みルーム一覧</h2>
    <table>
    <% @reservations. each do |reservation| %>
      <tr>
        <th>ルーム名</th>
        <td><%=link_to reservation.post.room_name, reservation_path(reservation) %></td>
      </tr>
      <tr>
        <th>使用日数</th>
        <td><%= (reservation.end_date.to_date - reservation.start_date.to_date).to_i %> 日</td>
      </tr>
      <tr>
        <th>合計料金</th>
        <td>¥<%= reservation.post.room_price * ((reservation.end_date.to_date - reservation.start_date.to_date).to_i) %></td>
      </tr>
      <tr>
        <th>開始日</th>
        <td><%= reservation.start_date %></td>
      </tr>
      <tr>
        <th>終了日</th>
        <td><%= reservation.end_date %></td>
      </tr>
      <tr>
        <th>予約確定日時</th>
        <td><%= reservation.created_at %></td>
      </tr>
    <% end %>
    </table>
    <div>

app/views/reservations/new.html.erb
<div class = reservation_form>
  <h2>予約項目を入力する</h2>
  <%= form_with url: @reservation, url: {action: 'create'},local: true do |f| %>
    <% if @reservation.errors.any? %>
      <ul>
      <% @reservation.errors.full_messages. each do |msg| %>
        <li><%= msg %></li>
      </ul>
      <% end %>
    <% end %>
    <table>
      <tr>
        <th><%= f.label :start_date ,"開始日" %></th>
        <td><%= f.date_field :start_date %></td>
      </tr>
      <tr>
        <th><%= f.label :end_date ,"終了日" %></th>
        <td><%= f.date_field :end_date %></td>
      </tr>
      <tr>
        <th><%= f.label :num_people ,"人数" %></th>
        <td><%= f.number_field :num_people %></td>
      </tr>
    </table>
    <div>
      <ul>
        <li><%= f.submit "上記の内容で予約する" %></li>
      </ul>
    </div>
  <% end %>
</div>

app/views/reservations/show.html.erb
<div class = post_show>
  <table>
    <%= image_tag @post.image if @post.image.attached? %>
    <tr>
      <th>ルーム名</th>
      <td><%= @post.room_name %></td>
      </tr>
    <tr>
      <th>使用日数</th>
      <td><%= (@reservation.end_date.to_date - @reservation.start_date.to_date).to_i %> 日</td>
    </tr>
    <tr>
      <th>開始日</th>
      <td><%= @reservation.start_date %></td>
    </tr>
    <tr>
      <th>終了日</th>
      <td><%= @reservation.end_date %></td>
    </tr>
    <tr>
      <th>宿泊人数</th>
      <td><%= @reservation.num_people %></td>
    </tr>
    <tr>
      <th>合計料金</th>
      <td>¥<%= @post.room_price * ((@reservation.end_date.to_date - @reservation.start_date.to_date).to_i) %></td>
    </tr>
  </table>
  <div>
    <ul>
      <li><%= link_to "予約を変更する", "#"%></li>
      <li><%= link_to "予約一覧に戻る", reservations_path%></li>
    </ul>
  </div>
</div>

app/views/users/edit.html.erb
<div class = account&profile>
  <%= form_with model: @user, local: true do |f| %>
  <table>
    <tr>
        <th><%= f.label :name ,"名前" %></th>
        <td><%= f.text_field :name %></td>
    </tr>
    <tr>
        <th><%= f.label :image ,"プロフィール画像" %></th>
        <td><%= f.file_field :image_name %></td>
    </tr>
    <tr>
        <th><%= f.label :email ,"メールアドレス" %></th>
        <td><%= f.text_field :email %></td>
    </tr>
    <tr>
        <th><%= f.label :password ,"パスワード" %></th>
        <td><%= f.text_area :password %></td>
    </tr>
    <tr>
        <th><%= f.label :password_confirmation ,"パスワード確認" %></th>
        <td><%= f.text_area :password_confirmation %></td>
    </tr>
  </table>
<div>
  <ul>
    <li><%= f.submit "編集する"%></li>
    <li><%= link_to "宿泊先一覧に戻る", "#" %></li>
  </ul>
</div>
    <% end %>
</div>

app/views/users/login_form.html.erb
<h1>ログイン</h1>
<% if @error_message %>
  <%= @error_message %>
<% end %>
  <%= form_with url:login_path, local: true do |form| %>
    <%= form.label :"メールアドレス" %>
    <li>
      <%= form.email_field :email %>
    </li>
    <%= form.label :"パスワード" %>
    <li>
      <%= form.password_field :password %>
    </li>
    <%= form.label :"パスワード確認" %>
    <li>
      <%= form.password_field :password_confirmation %>
    </li>
    <%= form.submit "ログイン" %>
<% end %>

app/views/users/myrooms.html.erb
<div class = "rooms">
  <% if @user.posts.any? %>
    <h2>登録済みルーム一覧</h2>
    <table>
      <% @posts. each do |post| %>
        <tr>
          <th>ルームイメージ</th>
          <td><%= image_tag post.image if post.image.attached? %></td>
        </tr>
        <tr>
          <th>ルーム名</th>
          <td><%= post.room_name %></td>
        </tr>
        <tr>
          <th>エリア</th>
          <td><%= post.room_address %></td>
        </tr>
        <tr>
          <th>料金</th>
          <td><%= post.room_price %></td>
        </tr>
        <tr>
          <td><%= link_to "詳細を見る", post_path(post.id) %></td>
        </tr>
      <% end %>
    </table>
  <% end %>
</div>

app/views/users/new.html.erb
<div class = user_form>
  <h2>新しいアカウトを作成</h2>
  <%= form_with model: @user, local: true do |f| %>
    <% if @user.errors.any? %>
      <ul>
      <% @user.errors.full_messages. each do |msg| %>
        <li><%= msg %></li>
      </ul>
      <% end %>
    <% end %>
      <table>
          <tr>
              <th><%= f.label :name ,"名前" %></th>
              <td><%= f.text_field :name %></td>
          </tr>
          <tr>
              <th><%= f.label :email ,"メールアドレス" %></th>
              <td><%= f.text_field :email %></td>
          </tr>
          <tr>
              <th><%= f.label :password ,"パスワード" %></th>
              <td><%= f.text_area :password %></td>
          </tr>
          <tr>
              <th><%= f.label :password_confirmation ,"パスワード確認" %></th>
              <td><%= f.text_area :password_confirmation %></td>
          </tr>
      </table>
      <div>
          <ul>
              <li><%= f.submit "新しいアカウントを作成"%></li>
              <li><%= link_to "すでにアカウントをお持ちの方はログイン", "#" %></li>
          </ul>
      </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class = account&profile>
  <table>
    <tr>
      <th>ユーザーアイコン</th>
      <td><%= image_tag "/user_images/#{@user.image_name}" %></td>
    </tr>
    <tr>
      <th>名前</th>
      <td><%= @user.name %></td>
    </tr>
    <tr>
      <th>メールアドレス</th>
      <td><%= @user.email %></td>
    </tr>
    <tr>
      <th>パスワード</th>
      <td><%= @user.password %></td>
    </tr>
  </table>
  <div>
    <ul>
      <li><%= link_to "編集する", edit_user_path(@user)%></li>
      <li><%= link_to "宿泊先一覧に戻る", "#" %></li>
    </ul>
  </div>
</div>